### PR TITLE
[euler] some solutions

### PR DESCRIPTION
**Pull request by andreoss**

### CODE REVIEW

**Comment by paultcochrane** [comment]
Thanks!

**Comment by paultcochrane** [comment]
Actually, it turns out that your solution to problem 59 doesn't run.  At a minium the variables `$decrypted` and `$password` aren't defined before being used.  Could you please check out the current version of the repository and supply patches to the file?  That'd be great if you could!

Thanks in advance!

**Comment by andreoss** [comment]
I've refactored out some key lines before commit, sorry for that.
I've fixed this in another branch.

**Comment by zoffixznet** [comment]
Merged (#23). Thanks.

**Pull request merged**
